#!/usr/bin/env python

import sys
from project.csvparse import CSVParse
from project.settings import DB_NAME, DB_TABLE

# Retrieve arguments passed on command line
def get_args():
    if len(sys.argv) < 2:
        return None
    else:
        filename = sys.argv[1]

    return filename

def main():

    # Get specified file from user
    filename = get_args()
    if filename is None:
        print('Too few arguments, please specify a csv filename')
        return

    client = CSVParse(DB_NAME, DB_TABLE)

    success, inserted, total_rows = client.process_csv(filename)

    if success:
        success_str = (
            '''{0} records inserted, total records are {1}'''
            ).format(inserted, total_rows)
        print(success_str)

if __name__ == "__main__":
    main()